## your_project constraints
## 16-bit input and output pins

# Configuration voltage settings
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# SPI configuration for quad SPI flash
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

# Input pins (data_in) - Using Bank 34 LVCMOS25 pins
set_property PACKAGE_PIN A2 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[0]}]
set_property PACKAGE_PIN A3 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[1]}]
set_property PACKAGE_PIN A4 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[2]}]
set_property PACKAGE_PIN A5 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[3]}]
set_property PACKAGE_PIN B1 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[4]}]
set_property PACKAGE_PIN B2 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[5]}]
set_property PACKAGE_PIN B4 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[6]}]
set_property PACKAGE_PIN B5 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[7]}]
set_property PACKAGE_PIN B6 [get_ports {data_in[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[8]}]
set_property PACKAGE_PIN C1 [get_ports {data_in[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[9]}]
set_property PACKAGE_PIN C2 [get_ports {data_in[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[10]}]
set_property PACKAGE_PIN C3 [get_ports {data_in[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[11]}]
set_property PACKAGE_PIN C4 [get_ports {data_in[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[12]}]
set_property PACKAGE_PIN C5 [get_ports {data_in[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[13]}]
set_property PACKAGE_PIN D1 [get_ports {data_in[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[14]}]
set_property PACKAGE_PIN D3 [get_ports {data_in[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[15]}]

# Output pins (data_out) - Bank 34 LVCMOS25
set_property PACKAGE_PIN D4 [get_ports {data_out[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[0]}]
set_property PACKAGE_PIN E1 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[1]}]
set_property PACKAGE_PIN E2 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[2]}]
set_property PACKAGE_PIN E3 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[3]}]
set_property PACKAGE_PIN F2 [get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[4]}]
set_property PACKAGE_PIN F3 [get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[5]}]
set_property PACKAGE_PIN F4 [get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[6]}]
set_property PACKAGE_PIN G1 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[7]}]
set_property PACKAGE_PIN G2 [get_ports {data_out[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[8]}]
set_property PACKAGE_PIN G4 [get_ports {data_out[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[9]}]
set_property PACKAGE_PIN H1 [get_ports {data_out[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[10]}]
set_property PACKAGE_PIN H2 [get_ports {data_out[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[11]}]
set_property PACKAGE_PIN H3 [get_ports {data_out[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[12]}]
set_property PACKAGE_PIN H4 [get_ports {data_out[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[13]}]
set_property PACKAGE_PIN J1 [get_ports {data_out[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[14]}]
set_property PACKAGE_PIN J3 [get_ports {data_out[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_out[15]}]



